[book]
language = "en"
src = "src"
title = "Gutenberg documentation"

[build]
build-dir = "book"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["static/mermaid.min.js", "static/mermaid-init.js"]
